DROP EVENT IF EXISTS evt;

CREATE EVENT evt
ON SCHEDULE EVERY 1 HOUR
DO 
BEGIN
UPDATE Lists SET active=0 WHERE end_date<CURRENT_TIMESTAMP;
UPDATE Users_Roles SET active=0 WHERE end_date<CURRENT_TIMESTAMP;
END
     
